# backend/app/models/__init__.py

# MODELS
# SQLAlCHEMY - FASTAPI MODELS 
# REPRESENT DATABASE TABLE - DEFINE THE SHAPE OF DATA
# ENABLE INPUT VALIDATION
# PROVIDE AUTOMATIC ERROR HANDLING
# HANDLE DATA SERIALIZATION AND DESERIALIZATION
# IMPROVE TYPE HINTING AND AUTOCOMPLETION
# GENERATE AUTOMATIC API DOCUMENTATION
# ALLOW MODEL REUSABILITY ACROSS ENDPOINTS
# INTEGRATE WITH DATABASE ORM MODELS
# KEEP CODE CLEAN, CONSISTENT, AND MAINTAINABLE

# IMPORT ALL MODELS SO THEY ARE REGISTERED WITH BASE.METADATA
from .user import User
from .image import Image
from .library import Library