# backend/app/schemas/__init__.py
# This file can be empty

# SCHEMAS
# PYDANTIC SCHEMAS - FOR REQUEST / RESPONSE VALIDATION
# DEFINE STRUCTURE AND RULES FOR DATA TRANSFER
# VALIDATE INPUT AND OUTPUT DATA AUTOMATICALLY
# CONTROL WHAT FIELDS ARE EXPOSED OR HIDDEN
# CONVERT DATABASE OBJECTS INTO JSON-READY DATA
# ENSURE CONSISTENT DATA FORMATS ACROSS ENDPOINTS
# PROVIDE CLEAR DATA CONTRACTS BETWEEN FRONTEND AND BACKEND
# SEPARATE INTERNAL DATABASE MODELS FROM PUBLIC API MODELS
# IMPROVE SECURITY BY LIMITING EXPOSED FIELDS
# ENABLE EASY SERIALIZATION AND DESERIALIZATION
# KEEP CODE ORGANIZED, READABLE, AND MAINTAINABLE
