# backend/app/routes/__init__.py
# This file can be empty


# ROUTES
# ROUTES SHOULD IMPORT SCHEMAS NOT RE-DEFINE THEM
# ORGANIZE API ENDPOINTS INTO MODULAR, MAINTAINABLE COMPONENTS
# GROUP RELATED ROUTES LOGICALLY (E.G., USERS, ITEMS, LIBRARIES)
# KEEP THE MAIN FASTAPI APP FILE CLEAN AND SIMPLE
# ALLOW INDEPENDENT TESTING AND DEBUGGING OF ROUTE GROUPS
# ENABLE ROUTE PREFIXES AND TAGS FOR CONSISTENT URL STRUCTURE
# FACILITATE DEPENDENCY INJECTION (E.G., DB SESSIONS, AUTH) AT THE ROUTER LEVEL
# ENSURE CONSISTENT REQUEST VALIDATION AND RESPONSE MODELS BY IMPORTING SCHEMAS
# PREVENT SCHEMA DUPLICATION AND MAINTAIN SINGLE SOURCE OF TRUTH
# MAKE SCALING THE BACKEND EASIER BY ADDING NEW ROUTES WITHOUT CLUTTER
# PROMOTE SEPARATION OF CONCERNS BY KEEPING ROUTES DISTINCT FROM BUSINESS LOGIC

# Routes:

# Accept HTTP requests

# Validate input via schemas

# Call database logic

# Return responses

# Example responsibilities:

# POST /library → create a row

# GET /library → fetch rows

# DELETE /library/{id} → remove a row