# backend/app/models/image.py

from sqlalchemy import Column, Integer, String, ForeignKey, DateTime, JSON, Boolean, Table
from sqlalchemy.orm import relationship
from sqlalchemy.sql import func
from app.database.db import Base

# Optional many-to-many table for images ↔ albums
image_album_association = Table(
    "image_album_association",
    Base.metadata,
    Column("image_id", ForeignKey("images.id"), primary_key=True),
    Column("album_id", ForeignKey("albums.id"), primary_key=True),
)

class Image(Base):
    __tablename__ = "images"

    id = Column(Integer, primary_key=True, index=True)
    user_id = Column(Integer, ForeignKey("users.id"), nullable=False)  # Creator / owner
    s3_key = Column(String, nullable=False)  # Path in S3
    image_metadata = Column(JSON, default={})      # renamed from 'metadata'
    manual_tags = Column(JSON, default=[])         # User-added tags
    rekognition_tags = Column(JSON, default=[])    # Tags generated by AWS Rekognition
    favorite = Column(Boolean, default=False)      # Future favorite feature
    created_at = Column(DateTime(timezone=True), server_default=func.now())
    updated_at = Column(DateTime(timezone=True), onupdate=func.now())

    # Relationships
    albums = relationship("Album", secondary=image_album_association, back_populates="images")
    user = relationship("User", back_populates="images")
    access_rules = relationship("ImageAccessRules", back_populates="image", uselist=False)
